### ISSUE TITLE
Warnings following Credo 1.4.0 update

### ISSUE THREAD

**Issue by gcauchon** [mirego/credo_naming#10]
Credo `1.4.0` introduced a new [_validation of check params in config_](https://hexdocs.pm/credo/changelog.html#1-4-0) which prints the following warnings when using `CredoNaming` checks:

```shell
> mix credo --strict
** (config) CredoNaming.Check.Warning.AvoidSpecificTermsInModuleNames: unknown param `terms`.
** (config) CredoNaming.Check.Consistency.ModuleFilename: unknown param `excluded_paths`.
Checking 92 source files (this might take a while) ...
…
```

I think we need to change the way we are "using" `Credo.Check` to provide the missing options:

- `category`
- `param_defaults`
- `explanations`

https://hexdocs.pm/credo/Credo.Check.html

**Comment by remi** [comment]
Yep, that makes sense. Do you want to tackle this?

**Comment by gcauchon** [comment]
> Do you want to tackle this?

As soon as I have a few minutes to spare…

**Comment by sitch** [comment]
bump!
