### ISSUE TITLE
Support for enforcing team conventions

### ISSUE THREAD

**Issue by bglusman** [mirego/credo_naming#21]
We're considering trying to use credo to create and enforce some standards around module hierarchy/organization...  it's not a fully fleshed out plan yet, but I wonder if other people have similar needs/tools and if perhaps we can build or leverage something somewhat general for better community support, and if this would be a good place to do it if there's interest.  I'm imagining something like a way to represent the hierarchy of modules in one canonical place, and then the tool can warn or error if names from inside that hierarchy occur in locations other than that described by the hierarchy?  but like I said, it's not fully fleshed out yet, just want to explore the idea and others thoughts on the subject.

**Comment by remi** [comment]
Hi Brian,

I’m not sure how to approach this.

Would you be able to implement this convention using the [`valid_filename?` callback option](https://github.com/mirego/credo_naming#naming-conventions) or is it something more complex? What do you have in mind for implementation?

**Comment by bglusman** [comment]
Sorry I'm so late responding!  I didn't know about valid_filename? callback, that seems like a good starting place to experiment!

**Comment by remi** [comment]
@bglusman I’m going to close this. Hopefully `valid_filename?` helped you!
