### ISSUE TITLE
Finish Umbrella Support

### ISSUE THREAD

**Issue by prem-prakash** [mirego/credo_naming#23]
Umbrella support is unfinished:

```elixir
defmodule MyInternalApp.Graphql.Resolvers.TodoResolver do
...
end
```

`apps/my_internal_app/lib/graphql/resolvers/todo_resolver.ex`

this returns positive for inconsistency

**Comment by dantuck** [comment]
@prem-prakash any movement on this issue? If it is stale I can likely do some work to help resolve it.

**Comment by prem-prakash** [comment]
@dantuck I think https://github.com/mirego/credo_naming/pull/17 solved this issue

**Comment by dantuck** [comment]
Thank you @prem-prakash, I tested it in a large umbrella app and looks like it is working. Appreciate the quick response.
